### ISSUE TITLE
return

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/nodejs-modules#1]
https://github.com/DenisPitsul/nodejs-modules/blob/ad66142947d02df288b848526a49482d0f9fdd09/index.js#L6
- в таких випадках, де потрібно вийти з функції, та непринципово, яке значення функція повертає, для лаконічности часто записують коротше:
```javascript
    return console.error('Error reading current dir using readdir:', err);
```

**Comment by DenisPitsul** [comment]
Corrected in commit:
https://github.com/DenisPitsul/nodejs-modules/commit/eb41ed7d942426b251c6273584b17ae5f9d307d8
